/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernanceStaking } from './GovernanceStaking';
export * as factories from './factories';
export { GovernanceStaking__factory } from './factories/GovernanceStaking__factory';
